# Results will be saved to neosr/experiments/results/

name = "validate_8_35_compact_x1_ultraReduced"
model_type = "image"
scale = 1
#use_amp = true
#compile = true

[datasets.test_1]
name = "val_1"
type = "single"
dataroot_lq = 'C:\Users\Fernando\Documents\Unicamp\IA_376_GAN\workspace\dgm-2025.2\projects\super-video-decompression\data\processed\lq_34_10_splitdb\test\lq'
[val]
#tile = 200

[network_g]
type = "compact"
num_conv = 8  
num_feat = 35 

[path]
pretrain_network_g = 'C:\Users\Fernando\Documents\Unicamp\IA_376_GAN\workspace\dgm-2025.2\projects\super-video-decompression\src\third_party\neosr\experiments\train_8_35_compact_x1_bigonly Best Models\net_g_149400.pth'
